version: "3.9"

services:
  api-service:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      AI_SERVICE_BASE_URL: http://ai-service:8000
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=emotiondb;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: YourStrong!Passw0rd
    depends_on:
      - ai-service
      - sqlserver

  ai-service:
    build:
      context: ./ai-service
    ports:
      - "8000:8000"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: YourStrong!Passw0rd
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
